[tasks.build]
workspace = false
command = "cargo"
args = ["build"]

[tasks.build-mac-app]
workspace = false
dependencies = ["build"]
script = [
    """
    #!/usr/bin/env bash
    mkdir -p $CARGO_MAKE_CRATE_NAME.app/Contents/MacOS/
    cp target/debug/$CARGO_MAKE_CRATE_NAME $CARGO_MAKE_CRATE_NAME.app/Contents/MacOS/
    """
]

[tasks.run-mac-app]
workspace = false
dependencies = ["build-mac-app"]
script = [
    """
    #!/usr/bin/env bash
    open $CARGO_MAKE_CRATE_NAME.app
    """
]

[tasks.run-in-mac-app]
workspace = false
dependencies = ["build-mac-app"]
script = [
    """
    #!/usr/bin/env bash
    ./$CARGO_MAKE_CRATE_NAME.app/Contents/MacOS/$CARGO_MAKE_CRATE_NAME
    """
]
